# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(default='Sports', max_length=100),
            preserve_default=False,
        ),
    ]
